# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Fd"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE"
description = ""
homepage = "http://fejzic.dev"
tags = []
features = []
min_version = "0.41"

[author]
  name = "Nadir Fejzic"
  homepage = "http://fejzic.dev"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
